# Keybinds
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Options
set -g base-index 1
set-option -g allow-rename off
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Appearance
setw -g clock-mode-colour colour200
setw -g mode-style 'fg=black bg=colour198 bold'
set -g pane-border-style 'fg=colour198'
set -g pane-active-border-style 'fg=colour200'

set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=colour198'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=colour200'
set -g status-right ' %Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=colour198'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=colour198 bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=colour200]#F '

setw -g window-status-bell-style 'fg=colour200 bg=colour198 bold'

set -g message-style 'fg=colour200 bg=colour198 bold'
